#ifndef STEP_PARSER_VZCONFIG_H
#define STEP_PARSER_VZCONFIG_H

struct VzConfig {
    char EQUAL_SYMBOL;
    char NESTING_SYMBOL;
    char STRING_QUOTE_SYMBOL;
    char SPACE_SYMBOL;
    int TAB_SIZE;
};

#endif STEP_PARSER_VZCONFIG_H
